#!/bin/csh -f
# a simple way to test everything

set path = (scripts ${path})

set reg_test = 1

set parser = parser.sml
set run_parse = "fun run_parse (cmd, args) = if null args then OS.Process.failure else (parse (hd args); OS.Process.success);"
set parser_img = img.${parser}

set printer = printAST.sml
set run_printer = "fun run_printer (cmd, args) = if null args then OS.Process.failure else (printAST (parse (hd args)); OS.Process.success);"
set printer_img = img.${printer}

set interp = interpreter.sml
set run_interp = "fun run_interp (cmd, args) = if null args then OS.Process.failure else (interpret (hd args); OS.Process.success);"
set interp_img = img.${interp}

if (${reg_test}) then
echo "[--- Regression Testing ----]"
if (-f "${parser}") then
   compile ${parser} "${run_parse}" run_parse ${parser_img}
   if (${status} == 0) then
      run run1 0_regression/1_parser ${parser_img}.*
      rm ${parser_img}.*
   else
      echo "Compilation of ${parser} failed."
   endif
else
   echo "Missing ${parser}, skipping tests."
endif

if (-f "${printer}") then
   compile ${printer} "${run_printer}" run_printer ${printer_img}
   if (${status} == 0) then
      run run1AST 0_regression/2_3_ast_echo ${printer_img}.*
      rm ${printer_img}.*
   else
      echo "Compilation of ${printer} failed."
   endif
else
   echo "Missing ${printer}, skipping tests."
endif

if (-f "${interp}") then
   compile ${interp} "${run_interp}" run_interp ${interp_img}
   if (${status} == 0) then
      run run1 0_regression/4_eval ${interp_img}.*
      run run1 0_regression/4_type_error ${interp_img}.*
      rm ${interp_img}.*
   else
      echo "Compilation of ${interp} failed."
   endif
else
   echo "Missing ${interp}, skipping tests."
endif
endif

echo "[--- New Feature Testing ---]"

if (-f "${parser}") then
   compile ${parser} "${run_parse}" run_parse ${parser_img}
   if (${status} == 0) then
      run run1 1_parser ${parser_img}.*
      rm ${parser_img}.*
   else
      echo "Compilation of ${parser} failed."
   endif
else
   echo "Missing ${parser}, skipping tests."
endif

if (-f "${printer}") then
   compile ${printer} "${run_printer}" run_printer ${printer_img}
   if (${status} == 0) then
      run run1AST 2_3_ast_echo ${printer_img}.*
      rm ${printer_img}.*
   else
      echo "Compilation of ${printer} failed."
   endif
else
   echo "Missing ${printer}, skipping tests."
endif

if (-f "${interp}") then
   compile ${interp} "${run_interp}" run_interp ${interp_img}
   if (${status} == 0) then
      run run1 4_eval ${interp_img}.*
      run run1 4_type_error ${interp_img}.*
      rm ${interp_img}.*
   else
      echo "Compilation of ${interp} failed."
   endif
else
   echo "Missing ${interp}, skipping tests."
endif
